---
version: "2.1"
services:
  installer:
    image: nicholaswilde/haste:latest
    container_name: haste
    ports:
      - 7777:7777
    restart: unless-stopped
    volumes:
      - app:/app
volumes:
  app:
